"""Convert the checked-in Shiyi atlas to compact flash-resident indexed pixels.

Requires Pillow only when regenerating art; normal firmware/native tests use
its checked-in C include. Alpha is composited onto the pet room background.
"""

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "firmware/esp32/assets/shiyi-atlas.png"
OUTPUT = ROOT / "firmware/esp32/main/muse_pet_art.inc"
SIZE = 96


def build():
    source = Image.open(SOURCE).convert("RGBA")
    if source.size != (4 * SIZE, 4 * SIZE):
        raise ValueError("Shiyi atlas must contain sixteen 96px cells")
    paw = Image.open(ROOT / "firmware/esp32/assets/shiyi-paw-atlas.png").convert("RGBA")
    if paw.size != (4 * SIZE, 2 * SIZE):
        raise ValueError("Paw atlas must contain eight 96px cells")
    matte = Image.new("RGBA", (4 * SIZE, 6 * SIZE), "#14261f")
    matte.alpha_composite(source)
    matte.alpha_composite(paw, (0, 4 * SIZE))
    indexed = matte.convert("RGB").quantize(colors=256, method=Image.Quantize.MEDIANCUT)
    palette = indexed.getpalette()
    colors = []
    for i in range(256):
        r, g, b = palette[3 * i : 3 * i + 3]
        colors.append(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3))
    lines = [
        "/* Generated by scripts/build_pet_art.py from the original Shiyi atlas. */",
        "static const uint16_t shiyi_palette[256] = {",
    ]
    for i in range(0, 256, 16):
        lines.append("    " + ",".join(f"0x{c:04x}" for c in colors[i : i + 16]) + ",")
    lines.extend(["};", "static const uint8_t shiyi_art[24][96 * 96] = {"])
    for frame in range(24):
        x, y = frame % 4 * SIZE, frame // 4 * SIZE
        data = list(indexed.crop((x, y, x + SIZE, y + SIZE)).getdata())
        lines.append("    {")
        for i in range(0, len(data), 32):
            lines.append("        " + ",".join(str(v) for v in data[i : i + 32]) + ",")
        lines.append("    },")
    lines.append("};\n")
    OUTPUT.write_text("\n".join(lines))
    print("Built 24 96px poses: 221184 indexed bytes + 512 palette bytes in flash")


if __name__ == "__main__":
    build()
